# LOADING DATA

In [ ]:
import os
import sqlite3
import pandas as pd
import kagglehub

# Download
path = kagglehub.dataset_download("guillemservera/tennis")

# Find the sqlite file inside the downloaded folder
sqlite_path = os.path.join(path, "database.sqlite")
print("SQLite file:", sqlite_path)

# Connect
conn = sqlite3.connect(sqlite_path)

# List tables
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """,
    conn
)
tables

Using Colab cache for faster access to the 'tennis' dataset.
SQLite file: /kaggle/input/tennis/database.sqlite

       name
0   matches
1   players
2  rankings

In [ ]:
matches = pd.read_sql_query("SELECT * FROM matches;", conn)

In [ ]:
matches.shape

(947720, 81)

In [ ]:
matches.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points',
       'winner1_id', 'winner2_id', 'loser1_id', 'loser2_id', 'winner1_name',
       'winner1_hand', 'winner1_ht', 'winner1_ioc', 'winner1_age',
       'winner2_name', 'winner2_hand', 'winner2_ht', 'winner2_ioc',
       'winner2_age', 'loser1_name', 'loser1_hand', 'loser1_ht', 'loser1_ioc',
       'loser1_age', 'loser2_name', 'loser2_hand', 'loser2_ht', 'loser2_ioc',
       'loser2_age', 'winner1_rank', 'winner1_rank_points', 'winner2_rank',
       'winner2_rank_points', 'loser1_rank', 'loser1_rank_points',
       'loser2_rank', 'loser2_rank_points'],
      dtype='object')

In [ ]:
#find number of missing scores from matches
matches['score'].isna().sum() #KEEP

#find number of missing minutes
matches['minutes'].isna().sum() #This is missing lots of rows, not worth keeping

#See if matches has a value of F
matches['round'].value_counts(10)

#check for specifically if F shows up
matches[matches['round'] == 'R128']

#see how many round information is missing
matches['round'].isna().sum() #KEEP

matches['winner_seed'].isna().sum() #Lots of missing, not worth keeping

#Inspection of winner_entry
matches['winner_entry'].isna().sum() #lots missing, not worth keeping

np.int64(772157)

In [ ]:
matches_cleaned = matches[
    ['tourney_id', 'tourney_name', 'surface', 'draw_size',
     'tourney_level', 'tourney_date', 'match_num',
     'winner_id', 'loser_id', 'score', 'round']
]

In [ ]:
matches_cleaned.shape

(947720, 11)

In [ ]:
matches_cleaned.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'loser_id', 'score', 'round'],
      dtype='object')

In [ ]:
matches_cleaned.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,Brisbane,Hard,32,A,20180101.0,271,105992.0,104919.0,6-4 3-6 6-2,R32
1,2018-M020,Brisbane,Hard,32,A,20180101.0,272,111577.0,111442.0,6-2 6-4,R32
2,2018-M020,Brisbane,Hard,32,A,20180101.0,273,104797.0,106000.0,6-7(4) 6-3 6-2,R32
3,2018-M020,Brisbane,Hard,32,A,20180101.0,275,200282.0,105449.0,7-6(7) 6-4,R32
4,2018-M020,Brisbane,Hard,32,A,20180101.0,276,111581.0,105643.0,6-3 6-4,R32

In [ ]:
players = pd.read_sql_query("SELECT * FROM players where dob > '19250101';", conn)

In [ ]:
players.shape

(45152, 8)

In [ ]:
players.columns

Index(['player_id', 'name_first', 'name_last', 'hand', 'dob', 'ioc', 'height',
       'wikidata_id'],
      dtype='object')

In [ ]:
players.head()

   player_id name_first name_last hand         dob  ioc  height wikidata_id
0     100003      Frank   Sedgman    R  19271002.0  AUS   180.0     Q962049
1     100004   Giuseppe     Merlo    R  19271011.0  ITA     NaN    Q1258752
2     100005    Richard  Gonzalez    R  19280509.0  USA   188.0      Q53554
3     100006      Grant    Golden    R  19290821.0  USA   175.0    Q3115390
4     100007        Abe     Segal    L  19301023.0  RSA     NaN    Q1258527

In [ ]:
rankings = pd.read_sql_query("SELECT * FROM rankings ;", conn)

In [ ]:
import pandas as pd

# Display head of rankings dataframe
display(rankings.head())

# Get the minimum ranking date
min_ranking_date = rankings['ranking_date'].min()
print(f"Minimum ranking date: {min_ranking_date}")

# Get the head of the lowest unique ranking dates, with one entry per date
display(rankings.drop_duplicates(subset=['ranking_date']).sort_values(by='ranking_date').head(20))

   ranking_date  rank  player  points
0      20000110     1  101736  4135.0
1      20000110     2  102338  2915.0
2      20000110     3  101948  2419.0
3      20000110     4  103017  2184.0
4      20000110     5  102856  2169.0

Minimum ranking date: 19730827

         ranking_date  rank  player  points
3214913      19730827   129  100005     NaN
3215103      19730917   168  100004     NaN
3215303      19731001   161  100004     NaN
3215517      19731015   158  100004     NaN
3215735      19731105   162  100004     NaN
3215962      19731126   175  100004     NaN
3216197      19731217   177  100004     NaN
3216434      19740304   179  100004     NaN
3216673      19740422   176  100004     NaN
3216909      19740506   185  100004     NaN
3217146      19740603   274  100003     NaN
3217442      19740729   109  100005     NaN
3217739      19740812   306  100003     NaN
3218048      19740909   312  100003     NaN
3218362      19740930   282  100003     NaN
3218678      19741111   297  100003     NaN
3219020      19741223   318  100003     NaN
3219396      19750120   323  100003     NaN
3219772      19750310   355  100002     NaN
3220175      19750414   383  100002     NaN

In [ ]:
rankings.shape

(3235639, 4)

In [ ]:
rankings.columns

Index(['ranking_date', 'rank', 'player', 'points'], dtype='object')

In [ ]:
rankings.sort_values(by='ranking_date', ascending=True)

         ranking_date  rank  player  points
3214959      19730827     7  100087     NaN
3214928      19730827    86  100045     NaN
3214929      19730827    67  100047     NaN
3214962      19730827    44  100091     NaN
3214963      19730827    34  100092     NaN
...               ...   ...     ...     ...
3214876      20240527  2032  211667     1.0
3212845      20240527     7  134770  4425.0
3214907      20240527  2067  209253     1.0
3214911      20240527  2073  202079     1.0
3214912      20240527  2073  207982     1.0

[3235639 rows x 4 columns]

# SUMMARY STATS

### Matches Stats

In [ ]:
matches_cleaned['draw_size'] = pd.to_numeric(matches_cleaned['draw_size'], errors='coerce').fillna(0).astype('int64')
draw_size_avg = matches_cleaned['draw_size'].mean()
draw_size_std = matches_cleaned['draw_size'].std()

/tmp/ipykernel_3359/1853711219.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_cleaned['draw_size'] = pd.to_numeric(matches_cleaned['draw_size'], errors='coerce').fillna(0).astype('int64')

In [ ]:
print("Draw size average: " + str(draw_size_avg))
print("Draw size standard deviation: " + str(draw_size_std))

Draw size average: 38.55405182965433
Draw size standard deviation: 25.315063990644

In [ ]:
matches_cleaned['tourney_name'].value_counts().head(10)

tourney_name
Wimbledon          16799
US Open            16616
Roland Garros      13142
Australian Open    10360
Hard                6572
M15 Monastir        6477
Clay                4480
M15 Antalya         4318
Miami Masters       3842
Barcelona           3499
Name: count, dtype: int64

In [ ]:
matches_cleaned["tourney_level"].value_counts().head(10)

tourney_level
S     429781
C     186777
A     142283
G      57997
15     35662
M      27702
25     21110
D      19445
R      11420
L       1691
Name: count, dtype: int64

In [ ]:
players['hand'].value_counts()

hand
U    30587
R    13145
L     1406
A        7
Name: count, dtype: int64

In [ ]:
players["ioc"].value_counts().head(10)

ioc
USA    5786
ESP    2391
GER    2223
ITA    2076
FRA    1920
BRA    1823
AUS    1679
ARG    1489
GBR    1310
JPN    1127
Name: count, dtype: int64

In [ ]:
print("Player height average: " + str(players['height'].mean()))
print("Player height standard deviation: " + str(players['height'].std()))

Player height average: 183.78077753779698
Player height standard deviation: 6.5330795482172315

In [ ]:
print("Rankings points average: " + str(rankings['points'].mean()))
print("Rankings points standard deviation: " + str(rankings['points'].std()))

Rankings points average: 117.12910941862015
Rankings points standard deviation: 430.0144231447666

### Cleaning more

**MATCHES DATA**

In [ ]:
#drop rows with unclear match_num, need to know how many were dropped here
matches_cleaned = matches_cleaned.dropna(subset=['match_num'])

matches_cleaned['match_num'] = pd.to_numeric(matches_cleaned['match_num'], errors='coerce')

matches_cleaned = matches_cleaned.dropna(subset=['match_num'])

matches_cleaned.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,Brisbane,Hard,32,A,20180101.0,271.0,105992.0,104919.0,6-4 3-6 6-2,R32
1,2018-M020,Brisbane,Hard,32,A,20180101.0,272.0,111577.0,111442.0,6-2 6-4,R32
2,2018-M020,Brisbane,Hard,32,A,20180101.0,273.0,104797.0,106000.0,6-7(4) 6-3 6-2,R32
3,2018-M020,Brisbane,Hard,32,A,20180101.0,275.0,200282.0,105449.0,7-6(7) 6-4,R32
4,2018-M020,Brisbane,Hard,32,A,20180101.0,276.0,111581.0,105643.0,6-3 6-4,R32

In [ ]:
matches_cleaned.shape

(934407, 11)

In [ ]:
#how many unclear winner_id
matches_cleaned['winner_id'].isna().sum()
matches_cleaned['loser_id'].isna().sum()

np.int64(13086)

In [ ]:
#drop rows with unclear winner_id
matches_cleaned = matches_cleaned.dropna(subset=['winner_id'])

In [ ]:
matches_cleaned = matches_cleaned.dropna(subset=['loser_id'])

In [ ]:
#convert tourney_date to datetime
matches_cleaned['tourney_date'] = pd.to_datetime(matches_cleaned['tourney_date'], format='%Y%m%d')

In [ ]:
matches_cleaned.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,Brisbane,Hard,32,A,2018-01-01,271.0,105992.0,104919.0,6-4 3-6 6-2,R32
1,2018-M020,Brisbane,Hard,32,A,2018-01-01,272.0,111577.0,111442.0,6-2 6-4,R32
2,2018-M020,Brisbane,Hard,32,A,2018-01-01,273.0,104797.0,106000.0,6-7(4) 6-3 6-2,R32
3,2018-M020,Brisbane,Hard,32,A,2018-01-01,275.0,200282.0,105449.0,7-6(7) 6-4,R32
4,2018-M020,Brisbane,Hard,32,A,2018-01-01,276.0,111581.0,105643.0,6-3 6-4,R32

In [ ]:
#any missing tourney_id
matches_cleaned['tourney_id'].isna().sum() #NO

#any missing tourney_name
matches_cleaned['tourney_name'].isna().sum() #NO

#any missing surface
matches_cleaned['surface'].isna().sum() #YES --> need to figure this out

matches_cleaned['draw_size'].isna().sum() #NO

matches_cleaned['tourney_level'].isna().sum() #NO

matches_cleaned['tourney_date'].isna().sum() #NO

matches_cleaned['match_num'].isna().sum() #NO

matches_cleaned['winner_id'].isna().sum() #NO

matches_cleaned['loser_id'].isna().sum() #NO

matches_cleaned['score'].isna().sum() #YES

matches_cleaned['round'].isna().sum() #NO


#SO only issue here is the surface!

np.int64(0)

In [ ]:
#help me see the missing surfaces and the counts of tourney_name for each missing surface
matches_cleaned[matches_cleaned['surface'].isna()]['tourney_name'].value_counts()


#SHow me the New York matches that having missing surface
matches_cleaned[(matches_cleaned['surface'].isna()) & (matches_cleaned['tourney_name'] == 'New York')]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
601245,1972-2058,New York,None,64,A,1972-02-28,252.0,100130.0,100152.0,6-3 6-2,R64
601246,1972-2058,New York,None,64,A,1972-02-28,253.0,100231.0,100088.0,7-6 6-1,R64
601247,1972-2058,New York,None,64,A,1972-02-28,254.0,100229.0,100232.0,7-5 6-1,R64
601248,1972-2058,New York,None,64,A,1972-02-28,255.0,100012.0,100217.0,6-3 6-2,R64
601249,1972-2058,New York,None,64,A,1972-02-28,256.0,100135.0,100049.0,6-4 6-2,R64
...,...,...,...,...,...,...,...,...,...,...,...
721186,1975-2025,New York,None,32,A,1975-03-17,19.0,100058.0,107277.0,6-2 4-6 7-5,QF
721187,1975-2025,New York,None,32,A,1975-03-17,20.0,100342.0,100461.0,6-3 6-3,QF
721188,1975-2025,New York,None,32,A,1975-03-17,21.0,100284.0,100113.0,7-5 3-6 6-1,SF
721189,1975-2025,New York,None,32,A,1975-03-17,22.0,100342.0,100058.0,6-3 6-1,SF
721190,1975-2025,New York,None,32,A,1975-03-17,23.0,100342.0,100284.0,DEF,F

In [ ]:
import numpy as np


#Score does not have to be purely numeric, there can be defaults and retirements and stuff

#need to ensure that tournaments that are referencing the same tournament have proper tournament name

#show rows where tourney_name is US Open
matches_cleaned[matches_cleaned['tourney_name'] == 'Us Open']
matches_cleaned[matches_cleaned['tourney_name'] == 'US Open']

#Make all non numeric columns have capitals so to standardize everything

matches_cleaned['surface'] = matches_cleaned['surface'].str.upper().replace('NONE', np.nan)
matches_cleaned['tourney_name'] = matches_cleaned['tourney_name'].str.upper()

In [ ]:
matches_cleaned.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,BRISBANE,HARD,32,A,2018-01-01,271.0,105992.0,104919.0,6-4 3-6 6-2,R32
1,2018-M020,BRISBANE,HARD,32,A,2018-01-01,272.0,111577.0,111442.0,6-2 6-4,R32
2,2018-M020,BRISBANE,HARD,32,A,2018-01-01,273.0,104797.0,106000.0,6-7(4) 6-3 6-2,R32
3,2018-M020,BRISBANE,HARD,32,A,2018-01-01,275.0,200282.0,105449.0,7-6(7) 6-4,R32
4,2018-M020,BRISBANE,HARD,32,A,2018-01-01,276.0,111581.0,105643.0,6-3 6-4,R32

In [ ]:
#find rows where score is null
matches_cleaned['score'].isna().sum()

np.int64(156)

In [ ]:
#Fill null scores with "UNKNOWN"
matches_cleaned['score'] = matches_cleaned['score'].fillna('UNKNOWN')

In [ ]:
#Have a comma with a space between each space of the score, use apply method
matches_cleaned['score'] = matches_cleaned['score'].apply(lambda x: x.replace(' ', ', '))

In [ ]:
matches_cleaned.head(20)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,BRISBANE,HARD,32,A,2018-01-01,271.0,105992.0,104919.0,"6-4, 3-6, 6-2",R32
1,2018-M020,BRISBANE,HARD,32,A,2018-01-01,272.0,111577.0,111442.0,"6-2, 6-4",R32
2,2018-M020,BRISBANE,HARD,32,A,2018-01-01,273.0,104797.0,106000.0,"6-7(4), 6-3, 6-2",R32
3,2018-M020,BRISBANE,HARD,32,A,2018-01-01,275.0,200282.0,105449.0,"7-6(7), 6-4",R32
4,2018-M020,BRISBANE,HARD,32,A,2018-01-01,276.0,111581.0,105643.0,"6-3, 6-4",R32
5,2018-M020,BRISBANE,HARD,32,A,2018-01-01,277.0,104999.0,105441.0,"6-4, 7-5",R32
6,2018-M020,BRISBANE,HARD,32,A,2018-01-01,278.0,105238.0,106043.0,"6-4, 7-6(3)",R32
7,2018-M020,BRISBANE,HARD,32,A,2018-01-01,279.0,104547.0,124014.0,"6-3, 6-4",R32
8,2018-M020,BRISBANE,HARD,32,A,2018-01-01,280.0,105051.0,126207.0,"6-3, 6-2",R32
9,2018-M020,BRISBANE,HARD,32,A,2018-01-01,282.0,111202.0,104180.0,"6-3, 7-6(1)",R32
10,2018-M020,BRISBANE,HARD,32,A,2018-01-01,283.0,106378.0,133430.0,"6-7(5), 7-6(4), 6-4",R32
11,2018-M020,BRISBANE,HARD,32,A,2018-01-01,284.0,105357.0,105166.0,"7-6(4), 6-0",R32
12,2018-M020,BRISBANE,HARD,32,A,2018-01-01,286.0,105992.0,105870.0,"6-7(5), 6-4, 6-2",R16
13,2018-M020,BRISBANE,HARD,32,A,2018-01-01,287.0,104797.0,111577.0,"7-6(5), 6-2",R16
14,2018-M020,BRISBANE,HARD,32,A,2018-01-01,288.0,200282.0,105683.0,"6-4, 6-4",R16
15,2018-M020,BRISBANE,HARD,32,A,2018-01-01,289.0,111581.0,104999.0,"6-2, 5-7, 6-4",R16
16,2018-M020,BRISBANE,HARD,32,A,2018-01-01,290.0,105238.0,104547.0,"6-1, 6-2",R16
17,2018-M020,BRISBANE,HARD,32,A,2018-01-01,291.0,106401.0,105051.0,"6-7(3), 7-6(5), 6-2",R16
18,2018-M020,BRISBANE,HARD,32,A,2018-01-01,292.0,106378.0,111202.0,"7-6(3), 5-7, 6-4",R16
19,2018-M020,BRISBANE,HARD,32,A,2018-01-01,293.0,105777.0,105357.0,"4-6, 7-6(8), 6-3",R16

# ENd of Matches Data

#Useless Stuff Here

In [ ]:
matches_cleaned.duplicated(subset=['tourney_id', 'match_num']).sum()
#There are 2016 matches with duplciated tourney_id and match_num... we need to dig into this more

np.int64(2016)

In [ ]:
#Find duplicates of combines tourney_id and match_num
duplicates = matches_cleaned[matches_cleaned.duplicated(subset=['tourney_id', 'match_num'], keep=False)]
duplicates.head()

#sort the duplciates table by the combo if tourney_id and match_num
duplicates = duplicates.sort_values(by=['tourney_id', 'match_num'])

#look only into wimbledon matches
#duplicates = duplicates[duplicates['tourney_name'] == 'Wimbledon']


duplicates.head(20)


#So I think now that we should have the primary key be round, tourney_id and match_num

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
26324,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,100.0,105657.0,133430.0,"6-0, 4-6, 6-2",Q1
428432,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,100.0,104918.0,105723.0,"6-4, 4-6, 6-2, 6-0",R128
26325,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,101.0,125802.0,106293.0,"6-2, 6-2",Q1
428433,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,101.0,105373.0,106362.0,"7-6(4), 6-3, 4-6, 0-6, 6-4",R128
26326,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,102.0,106167.0,104251.0,"7-5, 7-6(4)",Q1
428434,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,102.0,104597.0,104571.0,"6-7(3), 6-4, 6-3, 7-6(1)",R128
26327,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,103.0,105376.0,105882.0,"6-4, 6-7(5), 6-4",Q1
428435,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,103.0,105223.0,105550.0,"6-2, 6-1, 6-4",R128
26328,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,104.0,109054.0,106361.0,"2-6, 6-3, 6-4",Q1
428436,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,104.0,104545.0,111442.0,"6-3, 4-6, 7-6(5), 6-3",R128
26329,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,105.0,105936.0,105032.0,"3-6, 7-6(3), 6-2",Q1
428437,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,105.0,103893.0,105575.0,"6-0, 6-2, 6-4",R128
26330,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,106.0,104216.0,105656.0,"7-5, 6-1",Q1
428438,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,106.0,111575.0,111797.0,"6-4, 3-6, 7-6(4), 6-1",R128
26331,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,107.0,105963.0,105782.0,"7-6(2), 6-0",Q1
428439,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,107.0,104607.0,105526.0,"6-1, 6-1, 4-6, 6-4",R128
26332,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,108.0,111797.0,105487.0,"5-2, RET",Q1
428440,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,108.0,104269.0,100644.0,"6-4, 3-6, 6-4, 6-2",R128
26333,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,109.0,122078.0,103105.0,"6-2, 6-4",Q1
428441,2017-520,ROLAND GARROS,CLAY,128,G,2017-05-29,109.0,105732.0,111577.0,"6-4, 7-6(5), 6-4",R128

In [ ]:
matches_cleaned.duplicated(subset=['tourney_id', 'match_num', 'round']).sum()

#This looks perfect now!

np.int64(0)

In [ ]:
#Now room for other cleaning things for matches data...


matches_cleaned.head()


#what is the earliest match in the data
matches_cleaned["tourney_date"].min() #good, on par with the cutoff for rankings and player information

matches_cleaned.head(20)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,loser_id,score,round
0,2018-M020,BRISBANE,HARD,32,A,2018-01-01,271.0,105992.0,104919.0,"6-4, 3-6, 6-2",R32
1,2018-M020,BRISBANE,HARD,32,A,2018-01-01,272.0,111577.0,111442.0,"6-2, 6-4",R32
2,2018-M020,BRISBANE,HARD,32,A,2018-01-01,273.0,104797.0,106000.0,"6-7(4), 6-3, 6-2",R32
3,2018-M020,BRISBANE,HARD,32,A,2018-01-01,275.0,200282.0,105449.0,"7-6(7), 6-4",R32
4,2018-M020,BRISBANE,HARD,32,A,2018-01-01,276.0,111581.0,105643.0,"6-3, 6-4",R32
5,2018-M020,BRISBANE,HARD,32,A,2018-01-01,277.0,104999.0,105441.0,"6-4, 7-5",R32
6,2018-M020,BRISBANE,HARD,32,A,2018-01-01,278.0,105238.0,106043.0,"6-4, 7-6(3)",R32
7,2018-M020,BRISBANE,HARD,32,A,2018-01-01,279.0,104547.0,124014.0,"6-3, 6-4",R32
8,2018-M020,BRISBANE,HARD,32,A,2018-01-01,280.0,105051.0,126207.0,"6-3, 6-2",R32
9,2018-M020,BRISBANE,HARD,32,A,2018-01-01,282.0,111202.0,104180.0,"6-3, 7-6(1)",R32
10,2018-M020,BRISBANE,HARD,32,A,2018-01-01,283.0,106378.0,133430.0,"6-7(5), 7-6(4), 6-4",R32
11,2018-M020,BRISBANE,HARD,32,A,2018-01-01,284.0,105357.0,105166.0,"7-6(4), 6-0",R32
12,2018-M020,BRISBANE,HARD,32,A,2018-01-01,286.0,105992.0,105870.0,"6-7(5), 6-4, 6-2",R16
13,2018-M020,BRISBANE,HARD,32,A,2018-01-01,287.0,104797.0,111577.0,"7-6(5), 6-2",R16
14,2018-M020,BRISBANE,HARD,32,A,2018-01-01,288.0,200282.0,105683.0,"6-4, 6-4",R16
15,2018-M020,BRISBANE,HARD,32,A,2018-01-01,289.0,111581.0,104999.0,"6-2, 5-7, 6-4",R16
16,2018-M020,BRISBANE,HARD,32,A,2018-01-01,290.0,105238.0,104547.0,"6-1, 6-2",R16
17,2018-M020,BRISBANE,HARD,32,A,2018-01-01,291.0,106401.0,105051.0,"6-7(3), 7-6(5), 6-2",R16
18,2018-M020,BRISBANE,HARD,32,A,2018-01-01,292.0,106378.0,111202.0,"7-6(3), 5-7, 6-4",R16
19,2018-M020,BRISBANE,HARD,32,A,2018-01-01,293.0,105777.0,105357.0,"4-6, 7-6(8), 6-3",R16

In [ ]:
#I want a head of different tourney_id values, unique values
matches_cleaned['tourney_id'].value_counts().head(20)

tourney_id
2013-580    239
2017-560    239
2017-580    239
2015-540    239
2010-520    239
2020-580    239
2020-520    239
2005-560    239
2018-520    239
2005-520    239
2005-540    239
2014-540    239
2018-560    239
2003-520    239
2017-540    239
2012-560    239
2012-580    239
2012-520    239
2012-540    239
2004-580    239
Name: count, dtype: int64

In [ ]:
#More code to clean anything else up that seems off for matches!

# End of Useless Stuff

#PLAYERS DATA

In [ ]:
#convert dob to datetime
players['dob'] = pd.to_datetime(players['dob'], format='%Y%m%d', errors='coerce')

In [ ]:
#drop wikidata_id
players = players.drop('wikidata_id', axis=1)

In [ ]:
players

,player_id,name_first,name_last,hand,dob,ioc,height
0,100003,Frank,Sedgman,R,1927-10-02,AUS,180.0
1,100004,Giuseppe,Merlo,R,1927-10-11,ITA,NaN
2,100005,Richard,Gonzalez,R,1928-05-09,USA,188.0
3,100006,Grant,Golden,R,1929-08-21,USA,175.0
4,100007,Abe,Segal,L,1930-10-23,RSA,NaN
...,...,...,...,...,...,...,...
45147,212720,Juan Carlos,Fuentes Vasquez,U,2005-09-17,ESA,NaN
45148,212721,Benedict,Badza,U,2005-05-19,ZIM,NaN
45149,212722,Kwok Shun Dasson,Chan,U,2005-07-16,HKG,NaN
45150,212731,None,None,U,2002-10-02,USA,NaN
45151,212829,Ian,Mayew,U,2006-11-30,USA,NaN

In [ ]:
#check if player_id is missing
players['player_id'].isna().sum() #NO

np.int64(0)

In [ ]:
#How to handle None as a first name and last name?


#Select rows where name_first is "None"
print(players[players['name_first'].isna()].shape[0])

#do the same for last name
print(players[players['name_last'].isna()].shape[0])

#Change the hand U value to UNKNOWN
players['hand'] = players['hand'].str.upper().replace('U', 'UNKNOWN')

2
2

In [ ]:
players.head(30)
#see rows with players hand UNKNWOWN
players[players['hand'] == 'UNKNOWN']

,player_id,name_first,name_last,hand,dob,ioc,height
210,100213,Fred,Hemmes,UNKNOWN,1950-06-14,NED,NaN
2029,102032,Gustavo,Gomez,UNKNOWN,1972-03-17,ARG,NaN
2088,102091,Luis Ernesto,Peon Sr,UNKNOWN,1972-07-24,MEX,NaN
2173,102176,Arnaud,Magnin,UNKNOWN,1973-02-19,FRA,NaN
2264,102267,Gwinyai,Tongoona,UNKNOWN,1973-10-10,ZIM,NaN
...,...,...,...,...,...,...,...
45147,212720,Juan Carlos,Fuentes Vasquez,UNKNOWN,2005-09-17,ESA,NaN
45148,212721,Benedict,Badza,UNKNOWN,2005-05-19,ZIM,NaN
45149,212722,Kwok Shun Dasson,Chan,UNKNOWN,2005-07-16,HKG,NaN
45150,212731,None,None,UNKNOWN,2002-10-02,USA,NaN
45151,212829,Ian,Mayew,UNKNOWN,2006-11-30,USA,NaN

In [ ]:
#Change all Nan to UNKNOWN, except for dob
players[['player_id', 'name_first', 'name_last', 'hand', 'ioc', 'height']] = players[['player_id', 'name_first', 'name_last', 'hand', 'ioc', 'height']].fillna('UNKNOWN')

In [ ]:
players.head(30)

    player_id  name_first       name_last hand        dob  ioc   height
0      100003       Frank         Sedgman    R 1927-10-02  AUS    180.0
1      100004    Giuseppe           Merlo    R 1927-10-11  ITA  UNKNOWN
2      100005     Richard        Gonzalez    R 1928-05-09  USA    188.0
3      100006       Grant          Golden    R 1929-08-21  USA    175.0
4      100007         Abe           Segal    L 1930-10-23  RSA  UNKNOWN
5      100008        Kurt         Nielsen    R 1930-11-19  DEN  UNKNOWN
6      100009      Istvan          Gulyas    R 1931-10-14  HUN  UNKNOWN
7      100010        Luis           Ayala    R 1932-09-18  CHI    170.0
8      100011      Torben          Ulrich    L 1928-10-04  DEN    180.0
9      100012      Nicola     Pietrangeli    R 1933-09-11  ITA    178.0
10     100013       Neale          Fraser    L 1933-10-03  AUS    185.0
11     100014      Trevor         Fancutt    R 1934-07-14  RSA  UNKNOWN
12     100015       Sammy       Giammalva    R 1934-08-01  USA    180.0
13     100016         Ken        Rosewall    R 1934-11-02  AUS    175.0
14     100017         Mal        Anderson    R 1935-03-03  AUS  UNKNOWN
15     100018       Barry          Mackay    R 1935-08-31  USA    190.0
16     100019     Wieslaw        Gasiorek    R 1936-01-13  POL  UNKNOWN
17     100020   Alejandro          Olmedo    R 1936-03-24  PER    178.0
18     100021      Ashley          Cooper    R 1936-09-15  AUS    178.0
19     100022         Roy         Emerson    R 1936-11-03  AUS    183.0
20     100023  Ramanathan        Krishnan    R 1937-04-11  IND  UNKNOWN
21     100024    Jan Erik       Lundquist    R 1937-04-14  SWE    191.0
22     100025       Barry  Phillips Moore    R 1937-07-09  AUS    173.0
23     100026      Andres          Gimeno    R 1937-08-03  ESP    185.0
24     100027        Gene           Scott    R 1937-12-28  USA    185.0
25     100028      Manuel         Santana    R 1938-05-10  ESP    170.0
26     100029         Rod           Laver    L 1938-08-09  AUS    173.0
27     100030        Fred          Stolle    R 1938-10-08  AUS    190.0
28     100031     Dimitri         Sturdza    R 1938-11-10  SUI  UNKNOWN
29     100032    Patricio   Rodriguez Chi    R 1938-12-20  CHI    188.0

In [ ]:
#help verify if there are any nans left anywhere in the table
players.isna().sum()

player_id     0
name_first    0
name_last     0
hand          0
dob           4
ioc           0
height        0
dtype: int64

In [ ]:
#change last name and first name to all caps
players['name_first'] = players['name_first'].str.upper()
players['name_last'] = players['name_last'].str.upper()

In [ ]:
players.head()

   player_id name_first name_last hand        dob  ioc   height
0     100003      FRANK   SEDGMAN    R 1927-10-02  AUS    180.0
1     100004   GIUSEPPE     MERLO    R 1927-10-11  ITA  UNKNOWN
2     100005    RICHARD  GONZALEZ    R 1928-05-09  USA    188.0
3     100006      GRANT    GOLDEN    R 1929-08-21  USA    175.0
4     100007        ABE     SEGAL    L 1930-10-23  RSA  UNKNOWN

In [ ]:
#Any duplicate first name and last name combinations
players.duplicated(subset=['name_first', 'name_last']).sum()

np.int64(205)

## WHAT TO DO HERE? --> not sure there is anything to do here actually, could do record linking to indicate when two people are the same, and create a flag variable for this


Then when we query, we just choose the information that has more info about the person, like fewer nans

In [ ]:
#I want to view these duplciate
duplicates = players[players.duplicated(subset=['name_first', 'name_last'], keep=False)]
duplicates = duplicates.sort_values(by=['name_first', 'name_last'])
duplicates.head(10)

       player_id name_first    name_last     hand        dob  ioc   height
43915     209227      AARON        COHEN  UNKNOWN 2002-08-21  ISR  UNKNOWN
44026     209412      AARON        COHEN  UNKNOWN 2002-08-21  ISR  UNKNOWN
1717      101720    AGUSTIN     GARIZZIO        R 1970-03-19  ARG    185.0
38938     203602    AGUSTIN     GARIZZIO  UNKNOWN 1969-03-19  ARG  UNKNOWN
1336      101339    AGUSTIN       MORENO        R 1967-03-31  MEX    180.0
44080     209508    AGUSTIN       MORENO        R 1999-10-09  MEX    185.0
18698     126272         AJ  CATANZARITI  UNKNOWN 1995-08-21  USA  UNKNOWN
37050     200224         AJ  CATANZARITI  UNKNOWN 1995-08-21  USA  UNKNOWN
1868      101871  ALEXANDER      REICHEL        R 1971-03-03  USA    193.0
23230     131239  ALEXANDER      REICHEL        R 1971-03-09  USA  UNKNOWN

In [ ]:
#player_id unique?
players['player_id'].is_unique #yes

True

In [ ]:
def find_likely_duplicates(players, dob_tolerance_days=365):
    """
    Identifies pairs of players that are likely the same person
    based on name match and similar date of birth.

    Two players are flagged as likely the same person if:
    - They share the same first and last name AND
    - Their DOBs are within dob_tolerance_days OR share the same month and day (different year)

    Returns a dataframe of likely duplicate pairs.
    """
    from itertools import combinations
    import pandas as pd

    # Get all players with duplicate names
    name_counts = players.groupby(['name_first', 'name_last'])['player_id'].transform('count')
    dup_players = players[name_counts > 1].copy()

    likely_same = []

    # Group by name
    for (first, last), group in dup_players.groupby(['name_first', 'name_last']):
        if len(group) < 2:
            continue

        # Compare all pairs within same name group
        for (idx1, row1), (idx2, row2) in combinations(group.iterrows(), 2):
            try:
                dob1 = pd.to_datetime(row1['dob'])
                dob2 = pd.to_datetime(row2['dob'])
                dob_diff = abs((dob1 - dob2).days)

                # Check if within tolerance
                within_tolerance = dob_diff <= dob_tolerance_days

                # Check if same month and day regardless of year
                same_month_day = (dob1.month == dob2.month) and (dob1.day == dob2.day)

                likely_same_person = within_tolerance or same_month_day

            except:
                # If dob is missing/unparseable, flag as uncertain
                likely_same_person = None
                dob_diff = None
                same_month_day = None

            likely_same.append({
                'player_id_1': row1['player_id'],
                'player_id_2': row2['player_id'],
                'name': f"{first} {last}",
                'dob_1': row1['dob'],
                'dob_2': row2['dob'],
                'dob_diff_days': dob_diff,
                'same_month_day': same_month_day,
                'likely_same_person': likely_same_person
            })

    return pd.DataFrame(likely_same)

# Run it
duplicate_pairs = find_likely_duplicates(players)
print(f"Total duplicate name pairs: {len(duplicate_pairs)}")
print(f"Likely same person: {duplicate_pairs['likely_same_person'].sum()}")
print(f"Likely different people: {(duplicate_pairs['likely_same_person'] == False).sum()}")
print(f"Uncertain (missing DOB): {duplicate_pairs['likely_same_person'].isna().sum()}")
duplicate_pairs.head(10)

Total duplicate name pairs: 208
Likely same person: 174
Likely different people: 34
Uncertain (missing DOB): 0

,player_id_1,player_id_2,name,dob_1,dob_2,dob_diff_days,same_month_day,likely_same_person
0,209227,209412,AARON COHEN,2002-08-21,2002-08-21,0,True,True
1,101720,203602,AGUSTIN GARIZZIO,1970-03-19,1969-03-19,365,True,True
2,101339,209508,AGUSTIN MORENO,1967-03-31,1999-10-09,11880,False,False
3,126272,200224,AJ CATANZARITI,1995-08-21,1995-08-21,0,True,True
4,101871,131239,ALEXANDER REICHEL,1971-03-03,1971-03-09,6,False,True
5,104834,109613,ALEXANDRU DANIEL CARPEN,1986-11-24,1986-11-24,0,True,True
6,105232,109643,ANDRE PINHEIRO,1988-10-19,1988-10-19,0,True,True
7,100283,149054,ANDRE ZIETSMANN,1952-08-19,1954-08-19,730,True,True
8,102784,111349,ANDREAS WEBER,1976-04-26,1986-06-17,3704,False,False
9,122909,211346,ANDRES MARTIN,1976-02-02,2001-07-07,9287,False,False

In [ ]:





# # Create a mapping of player_id to likely_same_person flag
# # A player gets True if they appear in any likely_same_person=True pair

# likely_same_ids = set()

# for _, row in duplicate_pairs[duplicate_pairs['likely_same_person'] == True].iterrows():
#     likely_same_ids.add(row['player_id_1'])
#     likely_same_ids.add(row['player_id_2'])

# # Add flag to players — True if likely same person, NaN otherwise
# players['likely_duplicate'] = players['player_id'].apply(
#     lambda x: True if x in likely_same_ids else None
# )

# # Verify
# print(f"Players flagged as likely duplicates: {players['likely_duplicate'].sum()}")
# players[players['likely_duplicate'] == True].head(10)

#END Of Players Data

# RANKINGS DATA

In [ ]:
#convert ranking_date to datetime

rankings['ranking_date'] = pd.to_datetime(rankings['ranking_date'], format='%Y%m%d')

In [ ]:
rankings.sort_values(by='ranking_date', ascending=True)

        ranking_date  rank  player  points
3215010   1973-08-27   112  100163     NaN
3215035   1973-08-27    26  100220     NaN
3215036   1973-08-27   130  100223     NaN
3215037   1973-08-27    25  100229     NaN
3215038   1973-08-27    38  100231     NaN
...              ...   ...     ...     ...
3213523   2024-05-27   685  207340    45.0
3213522   2024-05-27   684  209302    45.0
3213521   2024-05-27   683  202269    45.0
3213551   2024-05-27   713  207249    40.0
3213359   2024-05-27   521  202146    77.0

[3235639 rows x 4 columns]

In [ ]:
rankings["ranking_date"].min()

Timestamp('1973-08-27 00:00:00')

In [ ]:
#check if some people have 0 points
rankings[rankings['points'] == 0.0]

#There are no players with 0 points, this doesnt seem to make sense

#how about people with 1 point
rankings[rankings['points'] ==1.0]

        ranking_date  rank  player  points
1297      2000-01-10  1299  100662     1.0
1298      2000-01-10  1299  100953     1.0
1299      2000-01-10  1299  101238     1.0
1300      2000-01-10  1299  101270     1.0
1301      2000-01-10  1299  101441     1.0
...              ...   ...     ...     ...
3214908   2024-05-27  2070  211388     1.0
3214909   2024-05-27  2071  210649     1.0
3214910   2024-05-27  2071  208890     1.0
3214911   2024-05-27  2073  202079     1.0
3214912   2024-05-27  2073  207982     1.0

[509799 rows x 4 columns]

Few problems going on here... firstly, combinations of ranking_date and rank have duplicates. This is fine because I realized that ranking_date and rank might not be the orimary key here, as multiple players with the same number of points can have the same ranking.

BUT I see a pprblem where ranking date and points are the same, but they have different ranks.

In [ ]:
#NEED TO ALTER THE PRIMARY KEY FOR THIS TABLE, cant be rank and ranking_date, needs to be the player and ranking_date


rankings.duplicated(subset=['ranking_date', 'player']).sum()


#show me the duplciate combos of ranking_date and player
duplicates = rankings[rankings.duplicated(subset=['ranking_date', 'player'], keep=False)]
duplicates = duplicates.sort_values(by=['ranking_date', 'player'])
duplicates.head(10)

        ranking_date  rank  player  points
3214933   1973-08-27   106  100054     NaN
3215099   1973-08-27   106  100054     NaN
3215081   1973-08-27   102  124487     NaN
3215102   1973-08-27   102  124487     NaN
3218309   1974-09-09   301  106859     NaN
3218361   1974-09-09   301  106859     NaN
3219310   1974-12-23   318  106859     NaN
3219395   1974-12-23   318  106859     NaN
3219685   1975-01-20   323  106859     NaN
3219771   1975-01-20   323  106859     NaN

In [ ]:
#Drop duplicates of all features combined
rankings = rankings.drop_duplicates()

In [ ]:
rankings.duplicated(subset=['ranking_date', 'player']).sum()

np.int64(513)

In [ ]:
duplicates = rankings[rankings.duplicated(subset=['ranking_date', 'player'], keep=False)]
duplicates = duplicates.sort_values(by=['ranking_date', 'player'])
duplicates.head(10)

        ranking_date  rank  player  points
3225282   1979-12-26   454  110788     NaN
3225381   1979-12-26   339  110788     NaN
1157240   1989-07-10   175  100905     NaN
1158060   1989-07-10   994  100905     NaN
1158493   1989-07-17   172  100905     NaN
1159330   1989-07-17  1010  100905     NaN
1159790   1989-07-24   199  100905     NaN
1160599   1989-07-24  1009  100905     NaN
1161041   1989-07-31   182  100905     NaN
1161887   1989-07-31  1029  100905     NaN

In [ ]:
# Keep the row with the lowest (best) rank for each player-date combination
rankings = rankings.sort_values('rank', ascending=True)
rankings = rankings.drop_duplicates(subset=['ranking_date', 'player'], keep='first')

In [ ]:
rankings.duplicated(subset=['ranking_date', 'player']).sum()

np.int64(0)

In [ ]:
#check if any missing ranking_date or player
rankings['ranking_date'].isna().sum() #NO
rankings['player'].isna().sum() #NO

np.int64(0)

# END Of Rankings Data

##Resolving the Unknown thing back to nans

In [ ]:
#Change UNKNOWN in matches_ data back to nans
matches_cleaned = matches_cleaned.replace('UNKNOWN', np.nan)

In [ ]:
#same for players data
players = players.replace('UNKNOWN', np.nan)

/tmp/ipykernel_3359/408094590.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  players = players.replace('UNKNOWN', np.nan)

In [ ]:
players.head()

   player_id name_first name_last hand        dob  ioc  height
0     100003      FRANK   SEDGMAN    R 1927-10-02  AUS   180.0
1     100004   GIUSEPPE     MERLO    R 1927-10-11  ITA     NaN
2     100005    RICHARD  GONZALEZ    R 1928-05-09  USA   188.0
3     100006      GRANT    GOLDEN    R 1929-08-21  USA   175.0
4     100007        ABE     SEGAL    L 1930-10-23  RSA     NaN

In [ ]:
import numpy as np
# players['likely_duplicate'] = players['likely_duplicate'].replace({None: np.nan})
players

,player_id,name_first,name_last,hand,dob,ioc,height
0,100003,FRANK,SEDGMAN,R,1927-10-02,AUS,180.0
1,100004,GIUSEPPE,MERLO,R,1927-10-11,ITA,NaN
2,100005,RICHARD,GONZALEZ,R,1928-05-09,USA,188.0
3,100006,GRANT,GOLDEN,R,1929-08-21,USA,175.0
4,100007,ABE,SEGAL,L,1930-10-23,RSA,NaN
...,...,...,...,...,...,...,...
45147,212720,JUAN CARLOS,FUENTES VASQUEZ,NaN,2005-09-17,ESA,NaN
45148,212721,BENEDICT,BADZA,NaN,2005-05-19,ZIM,NaN
45149,212722,KWOK SHUN DASSON,CHAN,NaN,2005-07-16,HKG,NaN
45150,212731,NaN,NaN,NaN,2002-10-02,USA,NaN
45151,212829,IAN,MAYEW,NaN,2006-11-30,USA,NaN

In [ ]:
players

,player_id,name_first,name_last,hand,dob,ioc,height
0,100003,FRANK,SEDGMAN,R,1927-10-02,AUS,180.0
1,100004,GIUSEPPE,MERLO,R,1927-10-11,ITA,NaN
2,100005,RICHARD,GONZALEZ,R,1928-05-09,USA,188.0
3,100006,GRANT,GOLDEN,R,1929-08-21,USA,175.0
4,100007,ABE,SEGAL,L,1930-10-23,RSA,NaN
...,...,...,...,...,...,...,...
45147,212720,JUAN CARLOS,FUENTES VASQUEZ,NaN,2005-09-17,ESA,NaN
45148,212721,BENEDICT,BADZA,NaN,2005-05-19,ZIM,NaN
45149,212722,KWOK SHUN DASSON,CHAN,NaN,2005-07-16,HKG,NaN
45150,212731,NaN,NaN,NaN,2002-10-02,USA,NaN
45151,212829,IAN,MAYEW,NaN,2006-11-30,USA,NaN

In [ ]:

rankings.dtypes
players.dtypes
matches_cleaned.dtypes

#EVERYTHING should be clean now!

Note the primary key changes, for ranking and for matches. Players didnt change, although player_id is technically unique, we have a indicator to tell if likely a duplcate player on not in the dataset.


matches_cleaned
players
rankings


need to now place these datasets in a database

In [ ]:
matches_cleaned.to_csv("matches", index=False)

In [ ]:
players.to_csv("players", index=False)

In [ ]:
rankings.to_csv("rankings", index=False)

In [ ]:
players.head()

* player id not null


*   name first can be null
*   name last can be null
*   hand can be null
*   dob can be null
*   ioc can be null
*   height can be null
*   likely_duplicate can be null

In [ ]:
#check for null dob
players['dob'].isna().sum()

In [ ]:
#check for null ioc
players['ioc'].isna().sum()

In [ ]:
players.dtypes

In [ ]:
print(players['likely_duplicate'].value_counts(dropna=False))
print(players['dob'].dtype)

In [ ]:
#change Nans to None instead


players = players.where(players.notna(), None)

players['dob'] = players['dob'].dt.date

In [ ]:
players

In [ ]:
players.head()

In [ ]:
#change every nan to None
players = players.where(players.notna(), None)

In [ ]:
players.head()

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine

# # Fix dob dtype
# players['dob'] = pd.to_datetime(players['dob'])

# engine = create_engine("postgresql://postgres:funwithfriends1!@database-1.cuwczqtqfgjs.us-east-1.rds.amazonaws.com:5432/postgres")

# players.to_sql("players", engine, schema="public", if_exists="replace", index=False)

In [ ]:
rankings.head()

In [ ]:
rankings.dtypes

In [ ]:
rankings['rank'].isna().sum()

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine

# # Fix dtypes
# rankings['ranking_date'] = pd.to_datetime(rankings['ranking_date'])

# # Replace NaNs
# rankings = rankings.where(rankings.notna(), None)

# # Fix float NaNs
# for col in rankings.select_dtypes(include='float').columns:
#     rankings[col] = rankings[col].astype(object).where(rankings[col].notna(), None)

# engine = create_engine("postgresql://postgres:funwithfriends1!@database-1.cuwczqtqfgjs.us-east-1.rds.amazonaws.com:5432/postgres")

# rankings.to_sql("rankings", engine, schema="public", if_exists="replace", index=False)

In [ ]:
matches_cleaned.head()

In [ ]:
matches_cleaned.dtypes

In [ ]:
#Check count of nulls per column in matches_cleaned
matches_cleaned.isna().sum()

In [ ]:
tournaments

CHECK HERE FOR MATCHES, we need to decompose matches into 3NF

In [ ]:
# import pandas as pd

# # starting dataframe: matches
# # assumes matches is your original pandas DataFrame

# # -----------------------------
# # 1. Build tournaments table
# # -----------------------------
# tournaments_1 = (
#     matches[
#         [
#             "tourney_id",
#             "tourney_name",
#             "surface",
#             "draw_size",
#             "tourney_level",
#             "tourney_date",
#         ]
#     ]
#     .drop_duplicates()
#     .reset_index(drop=True)
# )

# # optional sanity check:
# # each tourney_id should map to exactly one set of tournament attributes
# dupe_tourney_ids = tournaments_1["tourney_id"][tournaments_1["tourney_id"].duplicated()]
# if not dupe_tourney_ids.empty:
#     print("Warning: some tourney_id values map to multiple tournament records.")

# # -----------------------------
# # 2. Build matches table
# # -----------------------------
# matches_3nf = (
#     matches[
#         [
#             "tourney_id",
#             "match_num",
#             "round",
#             "winner_id",
#             "loser_id",
#             "score",
#         ]
#     ]
#     .drop_duplicates()
#     .reset_index(drop=True)
# )

# # -----------------------------
# # 3. Optional key checks
# # -----------------------------
# # tournaments: tourney_id should be unique
# assert tournaments_1["tourney_id"].is_unique, "tourney_id is not unique in tournaments"

# # matches: (tourney_id, match_num, round) should be unique
# assert not matches_3nf.duplicated(subset=["tourney_id", "match_num", "round"]).any(), \
#     "Composite key (tourney_id, match_num, round) is not unique in matches_3nf"

# # -----------------------------
# # 4. Optional: export to csv
# # -----------------------------
# tournaments_1.to_csv("tournaments.csv", index=False)
# matches_3nf.to_csv("matches_3nf.csv", index=False)

# print("Created tournaments and matches_3nf tables.")
# print("tournaments shape:", tournaments.shape)
# print("matches_3nf shape:", matches_3nf.shape)

In [ ]:
# tournaments_1['tourney_id'].groupby().count()
tournaments_1[['tourney_id','tourney_name']].groupby('tourney_id').count()

In [ ]:
tournaments_1[tournaments_1]

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine

# # Fix dtypes
# matches_cleaned['tourney_date'] = pd.to_datetime(matches_cleaned['tourney_date'])

# # Replace NaNs globally
# matches_cleaned = matches_cleaned.where(matches_cleaned.notna(), None)

# # Fix float columns (match_num, winner_id, loser_id, points)
# for col in ['match_num', 'winner_id', 'loser_id']:
#     if col in matches_cleaned.columns:
#         matches_cleaned[col] = matches_cleaned[col].astype(object).where(matches_cleaned[col].notna(), None)

# engine = create_engine("postgresql://postgres:funwithfriends1!@database-1.cuwczqtqfgjs.us-east-1.rds.amazonaws.com:5432/postgres")

# # Get valid player_ids from the players DataFrame
# valid_player_ids = players['player_id'].tolist()

# # Filter matches_cleaned to ensure winner_id and loser_id exist in valid_player_ids
# matches_cleaned = matches_cleaned[matches_cleaned['winner_id'].isin(valid_player_ids)]
# matches_cleaned = matches_cleaned[matches_cleaned['loser_id'].isin(valid_player_ids)]

# matches_cleaned.to_sql("matches", engine, schema="public", if_exists="replace", index=False)

#Tournament Table

In [ ]:
#Open up the atp_tournaments.csv and view head
atp_tourney = pd.read_csv("atp_tournaments.csv")
atp_tourney.head(30)

In [ ]:
import pandas as pd
# Load tournament reference table
atp_tourney = pd.read_csv('atp_tournaments.csv')
print(atp_tourney.shape)
atp_tourney.head(10)

In [ ]:
# Map category labels to tourney_level codes matching matches_cleaned convention
# G = Grand Slam  |  M = ATP Masters 1000  |  A = ATP 500 + ATP 250
cat_to_level = {
    'Grand Slam':       'G',
    'ATP Masters 1000': 'M',
    'ATP 500':          'A',
    'ATP 250':          'A',
}
atp_tourney['tourney_level'] = atp_tourney['category'].map(cat_to_level)

print('atp_tourney tourney_level distribution:')
print(atp_tourney['tourney_level'].value_counts())
print()
print('matches_cleaned G/M/A row counts for comparison:')
gma = matches_cleaned['tourney_level'].value_counts()
print(gma[gma.index.isin(['G','M','A'])])

In [ ]:
import re
from difflib import get_close_matches

# Case-normalised lookup: 'UPPER NAME' -> original value as stored in matches_cleaned
match_names_raw   = matches_cleaned['tourney_name'].dropna().unique()
match_names_upper = {n.upper().strip(): n for n in match_names_raw}

n_unique = len(match_names_upper)
sample   = sorted(list(match_names_upper.keys()))[:20]
print(f'{n_unique} unique tourney_name values in matches_cleaned')
print('Sample:', sample)

In [ ]:
# Manual overrides: tournament display names that don't match city or simple normalization
MANUAL = {
    'French Open (Roland Garros)':            'Roland Garros',
    'Italian Open':                            'Rome',
    'Canadian Open':                           'Montreal',    # alternates Montreal/Toronto year-by-year
    'Monte-Carlo Masters':                     'Monte-Carlo Masters',
    'Swiss Indoors':                           'Basel',
    'Swiss Open':                              'Gstaad',
    'Swedish Open':                            'Bastad',
    'Grand Prix Hassan II':                    'Casablanca',
    'Open Occitanie':                          'Montpellier',
    'Grand Prix Auvergne-Rh\u00f4ne-Alpes':    'Lyon',
    'Lib\u00e9ma Open':                        'Rosmalen',
    'Generali Open Kitzb\u00fchel':            'Kitzbuhel',
    'Paris Masters':                           'Paris Masters',
    "Queen's Club Championships":              "Queen's Club",
    'Hall of Fame Open (1976\u20132024)':       'Newport',
    'Hellenic Championship':                   'Athens',
    "U.S. Men's Clay Court Championships":     'Houston',
    'Winston-Salem Open':                      'Winston-Salem',
    'Eastbourne International':                'Eastbourne',
    'European Open':                           'Antwerp',
    'Bavarian International':                  'Munich',
    'Bavarian International (1899\u20132024)':  'Munich',
    'SA Tennis Open (2009\u20132011)':          'Johannesburg',
    'Srpska Open (2023)':                      'Banja Luka',
    'Bett1Hulks Cologne Championship (2020)':  'Cologne',
    'Bett1Hulks Cologne Indoors (2020)':       'Cologne',
    'Moselle Open (2003\u20132025)':            'Metz',
    'Washington Open':                         'Washington',
    'Miami Open':                              'Miami Masters',
}

def strip_year(name):
    """Remove parenthetical year ranges like (2021) or (2019-2024)."""
    return re.sub(r'\s*\([^)]*\)', '', str(name)).strip()

def normalize(s):
    """Uppercase, strip common generic words, remove non-alphanumeric."""
    s = strip_year(s)
    s = re.sub(r'\b(open|international|championships|series|indoors|indoor)\b', '', s, flags=re.I)
    s = re.sub(r"[^a-z0-9\s']", ' ', s.lower())
    return re.sub(r'\s+', ' ', s).strip().upper()

print('Manual overrides and normalization helpers ready.')

In [ ]:
def find_tourney_name(row):
    tournament = row['tournament']
    city       = str(row['city'])

    # 1. Manual override
    if tournament in MANUAL:
        candidate = MANUAL[tournament].upper()
        if candidate in match_names_upper:
            return match_names_upper[candidate]

    # 2. Exact city match (most ATP events are keyed by city in matches_cleaned)
    for c in [p.strip() for p in city.upper().split('/')]:
        if c in match_names_upper:
            return match_names_upper[c]

    # 3. Exact normalised tournament name
    norm_t = normalize(tournament)
    if norm_t in match_names_upper:
        return match_names_upper[norm_t]

    keys = list(match_names_upper.keys())

    # 4. Fuzzy match on normalised tournament name (high cutoff)
    fuzzy_t = get_close_matches(norm_t, keys, n=1, cutoff=0.75)
    if fuzzy_t:
        return match_names_upper[fuzzy_t[0]]

    # 5. Fuzzy match on city name
    fuzzy_c = get_close_matches(city.upper(), keys, n=1, cutoff=0.82)
    if fuzzy_c:
        return match_names_upper[fuzzy_c[0]]

    return None


atp_tourney['tourney_name'] = atp_tourney.apply(find_tourney_name, axis=1)

n_matched   = int(atp_tourney['tourney_name'].notna().sum())
n_unmatched = int(atp_tourney['tourney_name'].isna().sum())
print('Matched:  ', n_matched, '/', len(atp_tourney))
print('Unmatched:', n_unmatched)

In [ ]:
# Inspect unmatched rows
# These are typically very old or discontinued tournaments outside the matches dataset date range
unmatched_df = atp_tourney[atp_tourney['tourney_name'].isna()]
print(len(unmatched_df), 'unmatched:')
unmatched_df[['category','tournament','city','country']]

In [ ]:
# Verify the join between atp_tourney and matches_cleaned (ATP-level matches only)
join_preview = (
    matches_cleaned[matches_cleaned['tourney_level'].isin(['G','M','A'])]
    [['tourney_name','tourney_level']]
    .drop_duplicates()
    .merge(
        atp_tourney[['tourney_name','tournament','city','country','venue','tourney_level']],
        on='tourney_name',
        how='left',
        suffixes=('_matches','_atp')
    )
    .sort_values(['tourney_level_matches','tourney_name'])
    .reset_index(drop=True)
)

n_hit   = int(join_preview['tournament'].notna().sum())
n_total = len(join_preview)
hit_pct = round(n_hit / n_total * 100, 1)
print('Join hit rate:', hit_pct, '%  --', n_hit, '/', n_total, 'unique tournament-level combos matched')
join_preview.head(30)

In [ ]:
# Final column order for the atp_tournaments reference table
atp_tourney_final = atp_tourney[[
    'tourney_name',    # join key: matches matches_cleaned['tourney_name']
    'tournament',      # full Wikipedia display name
    'category',        # human-readable tier (Grand Slam / ATP Masters 1000 / ATP 500 / ATP 250)
    'tourney_level',   # single-letter code matching matches_cleaned  (G / M / A)
    'city',
    'country',
    'venue',
]].copy()

print(atp_tourney_final.shape)
atp_tourney_final.head(40)

#Adressing Naming Problems with the scrape torunaments

In [ ]:
import pandas as pd
atp_tourney_final_claude = pd.read_csv("atp_tourney_final.csv")
atp_tourney_final_claude.head(30)

In [ ]:
#download atp_tourney_final as a csv
atp_tourney_final.to_csv("atp_tourney_final.csv", index=False)

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine

# engine = create_engine("postgresql://postgres:funwithfriends1!@database-1.cuwczqtqfgjs.us-east-1.rds.amazonaws.com:5432/postgres")

# tournaments_df = (
#     atp_tourney_final_claude
#     [['tourney_name', 'tourney_level', 'city', 'country', 'venue']]
#     .where(lambda df: df.notna(), None)
#     .dropna()
# )

# tournaments_df.to_sql(
#     'tournaments', engine,
#     schema='public',
#     if_exists='replace',
#     index=False
# )
# print('Uploaded', len(tournaments_df), 'rows to tournaments')

In [ ]:
#find duplciates from the tournaments
tournaments_df.duplicated(subset=['tourney_name']).sum()

In [ ]:
#display duplicates so I can see them
tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)].sort_values(by=['tourney_name'])

In [ ]:
#eliminate exact duplicate rows from tournaments
tournaments_df = tournaments_df.drop_duplicates()

In [ ]:
tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)].sort_values(by=['tourney_name'])

In [ ]:
# Step 1: Uppercase all string columns
str_cols = ['tourney_name', 'city', 'country', 'venue']
tournaments_df[str_cols] = tournaments_df[str_cols].apply(lambda col: col.str.upper().str.strip())

# Step 2: Check duplicates again after uppercasing
tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)].sort_values('tourney_name')

In [ ]:
# Step 3: Manual resolution for known conflicts
# Keep the row with the correct/current venue per tournament
overrides = {
    'BELGRADE':       'SRPC MILAN GALE MUŠKATIROVIĆ',  # current arena
    'DALLAS':         'FORD CENTER AT THE STAR',         # correct city is Dallas
    'HAMBURG':        'AM ROTHENBAUM',                   # keep M-level (Masters) entry
    'LYON':           'LDLC ARENA',                      # current venue
    'ST. PETERSBURG': 'SIBUR ARENA',                     # keep either, drop city spelling dupe
    'STOCKHOLM':      'KUNGLIGA TENNISHALLEN',            # current venue
    'STUTTGART':      'TENNIS CLUB WEISSENHOF',          # current venue
}

def resolve_dupes(df):
    deduped = []
    for name, group in df.groupby('tourney_name'):
        if len(group) == 1:
            deduped.append(group)
        elif name in overrides:
            preferred = group[group['venue'] == overrides[name]]
            deduped.append(preferred if not preferred.empty else group.iloc[[-1]])
        else:
            deduped.append(group.iloc[[-1]])  # fallback: keep last
    return pd.concat(deduped).reset_index(drop=True)

tournaments_df = resolve_dupes(tournaments_df)

# Verify
print(tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)])
print(len(tournaments_df))

In [ ]:
#show me the head of the table now
tournaments_df.head(30)

#how many duplicate rows
tournaments_df.duplicated(subset=['tourney_name']).sum()

#show these duplciate rows
tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)].sort_values(by=['tourney_name'])

In [ ]:
# Drop index 28 (DALLAS/DALLAS) and index 93 (ST. PETERSBURG dupe), keep Frisco and either ST. PETE
tournaments_df = tournaments_df.drop(index=[28, 93]).reset_index(drop=True)

# Verify
print(tournaments_df.duplicated(subset=['tourney_name']).sum())  # should be 0 remaining for these

In [ ]:
#show these duplciate rows
tournaments_df[tournaments_df.duplicated(subset=['tourney_name'], keep=False)].sort_values(by=['tourney_name'])

In [ ]:
tournaments_df.shape

In [ ]:
#Show duplciates for tournaments df
tournaments_df.duplicated(subset=['tourney_name']).sum()

In [ ]:
# #Now put into sql alchemy

# from sqlalchemy import create_engine

# engine = create_engine("postgresql://postgres:funwithfriends1!@database-1.cuwczqtqfgjs.us-east-1.rds.amazonaws.com:5432/postgres")

# # Ensure unique tourney_name before uploading, keeping the first occurrence
# tournaments_df = tournaments_df.drop_duplicates(subset=['tourney_name'], keep='first')

# tournaments_df.to_sql(
#     'tournaments', engine,
#     schema='public',
#     if_exists='append',
#     index=False
# )
# print('Uploaded', len(tournaments_df), 'rows to tournaments')